config/routes.rb
Rails.application.routes.draw do
  get '/books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'show_book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  get '/top' => 'homes#top'
  root to: 'homes#top'
  post '/books' => 'books#create'
  patch '/books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  
  def new
    @book = Book.new
  end
  
  def create
   
    @book = Book.new(book_params)
   
    @book.save
 
    redirect_to '/show'
  end

  def index
    @book = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redilect_to '/index'
  end
  
  private
  
  def book_params
   params.require(:book).permit(:title, :body)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to show_book_path(@book.id)
    else
      @books = Book.all 
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to show_book_path(@book.id)
    else
      @books = Book.all 
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/book/show.html.erb
 <p>
  <b>Title: </b>
  <%= @book.title %>
 </p>


 <p>
  <b>Body: </b>
  <%= @book.body %>
 </p>

 <p>
   <a href ='/edit'>Edit</a>
 </p>
 
 <p>
   <a href ='/index'>Back</a>
 </p>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>

  <%= @book.errors.count %> errors prohibited this book from being saved:
  
  <ul>
      
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    
  </ul>
  
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>
  
   <p>
     <%= f.submit 'Update Book' %>
   </p>
   <p>
     <%= link_to "Show", show_book_path(@book.id) %> |
     
     <a href ='/books'>Back</a>
   </p>
   

<% end %>

 

app/views/books/index.html.erb
<h1>Books</h1>

　<table>
　  <thead>
　   <tr> 
　   
      <th><p>Title</p></th>
      <th><p>Body</p></th>
      
     </tr>
    </thead>    
    
    <% @books.each do |book| %>
    
    <tbody>
     <tr align="left">
     
      <th>
      
        <span><%= book.title %></span>
     
      </th>
      
      <th>
      
        <span><%= book.body %></span>
     
      </th>
      
      <th>
       
        <%= link_to "Show", show_book_path(book.id) %>
      
      </th>
      
      <th>
       
          <%= link_to "Edit", edit_book_path(book.id) %>
     
      </th>
      
      <th>
       
        <%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure? "%>
      </th>
      
     </tr>
    </tbody>
  
   <% end %>
  
  </table>
  


<h2>New Book</h2>

<% if @book.errors.any? %>

  <%= @book.errors.count %> errors prohibited this book from being saved:
  
  <ul>
      
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    
  </ul>
  
<% end %>


<%= form_with model: @book do |f| %>
  <h5>Title</h5>
  <%= f.text_field :title %>
	
  <h5>Body</h5>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
 <p>
  <b>Title: </b>
  <%= @book.title %>
 </p>


 <p>
  <b>Body: </b>
  <%= @book.body %>
 </p>

 <p>
   <%= link_to "Edit", edit_book_path(@book.id) %> |
   <a href ='/books'>Back</a>
 </p>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ!
</h1>

<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>

<p>
  印象を共有し交換することができます
</p>

<p>
  <a href ='/books'>start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
   </main>
  </body>
</html>